name: CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unlock secrets
        uses: philips-forks/github-action-git-crypt-unlock@master
        env:
          GIT_CRYPT_KEY: "AEdJVENSWVBUS0VZAAAAAgAAAAAAAAABAAAABAAAAAAAAAADAAAAIF85B7kFpHjz49GStZm1ctyWQv+o3qvHlbAiMB/VgJQRAAAABQAAAEC4OV4QgSqUqF1ChA9uz6JT3F80yV5KjxMm6YqBZX+zRwsgWMqK+164ptiSy+Pfo+IrPH5boZfebV6IdCHl8/4NAAAAAA=="

      - name: GitHub Action to run shunit2 tests
        uses: TheColvinCo/shunit2-github-action@v1.3
        env:
          SHUNIT_TEST_FOLDER: "tests/"
